#!/bin/bash
set -e
mkdir -p proto/gen
for pkg in api aprs ax25; do
  mkdir -p pkg/$pkg
  protoc -I=$(pwd) \
    --cpp_out=proto/gen \
    --grpc_out=proto/gen \
    --plugin=protoc-gen-grpc=$(which grpc_cpp_plugin) \
    -I=proto \
    $pkg.proto
done

# Go proto options
#
#export PATH=$HOME/go/bin:$PATH
#    --go_out=pkg/$pkg \
#    --go_opt=paths=source_relative \
#    --go-grpc_out=pkg/$pkg \
#    --go-grpc_opt=paths=source_relative \
